name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        configuration: [Release]
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '10.0.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore --configuration ${{ matrix.configuration }}

      - name: Test
        run: dotnet test test/Particle.Tests/Particle.Tests.csproj --no-build --configuration ${{ matrix.configuration }} --logger "console;verbosity=minimal"

      - name: Pack
        run: dotnet pack src/Particle/Particle.csproj --no-build --configuration ${{ matrix.configuration }} --output ./artifacts

      - name: Publish NuGet package
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')
        env:
          NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
        run: |
          dotnet nuget push artifacts/*.nupkg \
            --api-key $NUGET_API_KEY \
            --source https://api.nuget.org/v3/index.json